#!/usr/bin/env python3

'''
Last update: v1, 12/30/20
This code takes in a search term and a .fasta input file, and then searches through that fasta file for entries with the search
term in the name. I originally made this to search for plasmids in order to depleat a big fasta file containing many different genome
sequences in fasta format of any entries with plasmids in them.
'''

import sys
from Bio import SeqIO

def remove_searchterm (searchterm, input, output):
    entrycounter = 0
    searchcounter = 0

    for entry in SeqIO.parse(input, "fasta"):
        entrycounter = entrycounter + 1
        seqname = str(entry.description)
        if searchterm not in seqname:
            searchcounter = searchcounter + 1
            with open (output, 'a') as fh:
                newentry = ">" + entry.description + "\n" + entry.seq + "\n"
                newentry = str(newentry)
                fh.write(newentry)

    print("There were {} total sequences in the file, and {} did not have the search term.".format(entrycounter, searchcounter))

if __name__ == '__main__':
    if len(sys.argv) == 4:
         remove_searchterm(sys.argv[1], sys.argv[2], sys.argv[3])
    else:
         print("Usage: search term, input.fasta, output.fasta ")
         sys.exit(0)
